### ISSUE TITLE
tegu_ha config file parsing bug

### ISSUE THREAD

**Issue by ScottDaniels** [att/tegu#19]
The tegu_ha.py script does not properly handle the case where the "fqmgr" section does not have the  phost_suffix defined.  This is a legitmate case, and the value used if the pair is missing from the control file should be the same as if phost_suffix = ""  were in the config file. 

Relevant trace:

> > ```
> > root@mtmac1:/var/log/tegu# cat tegu_ha.log
> > 2015/09/08 14:23 tegu_ha v1.1 started
> > Traceback (most recent call last):
> >   File "/usr/bin/tegu_ha", line 408, in <module>
> >     main()
> >   File "/usr/bin/tegu_ha", line 367, in main
> >     if not cdata["fqmgr"]["phost_suffix"]:
> > KeyError: 'phost_suffix'
> > ```

**Comment by ScottDaniels** [comment]
This issue has been addressed in commit: e818697930e163d7f85db2067e1a5141fe533d59
