### ISSUE TITLE
tegu_ha does not properly handle hostnames which do not have a domain

### ISSUE THREAD

**Issue by ScottDaniels** [att/tegu#20]
The tegu_ha.py script does not handle the case where a host name does not have an associated domain name (foo is returned instead of foo.somedom.com).   The script needs properly handle this case.

Relevant trace:

> > ```
> > 2015/09/08 14:28 tegu_ha v1.1 started
> > Traceback (most recent call last):
> >   File "/usr/bin/tegu_ha", line 408, in <module>
> >     main()
> >   File "/usr/bin/tegu_ha", line 374, in main
> >     + this_node[this_node.index("."):])
> > ValueError: substring not found
> > ```

**Comment by ScottDaniels** [comment]
This issue has been addressed in commit: e818697930e163d7f85db2067e1a5141fe533d59
